// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/metrics": {
            "get": {
                "description": "Returns the current metrics status",
                "tags": [
                    "Metrics"
                ],
                "summary": "Metrics Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/stats/{provider}": {
            "get": {
                "description": "Returns stats for the given provider (youtube, github, twitch, leetcode)",
                "tags": [
                    "Stats"
                ],
                "summary": "Get stats from a provider",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stats Provider",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/stream/status": {
            "get": {
                "description": "Returns whether the stream is currently active",
                "tags": [
                    "Stream"
                ],
                "summary": "Stream Status",
                "responses": {
                    "200": {
                        "description": "true or false",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "majesticcoding.com",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Majestic Coding API",
	Description:      "Go API for Full Stack Application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
