apiVersion: apps/v1
kind: Deployment
metadata:
  name: majesticcoding-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: majesticcoding
  template:
    metadata:
      labels:
        app: majesticcoding
    spec:
      containers:
        - name: majesticcoding
          image: {{ .Values.majesticcoding.image }}
          ports:
            - containerPort: {{ .Values.majesticcoding.port }}
          volumeMounts:
            - name: stream-data
              mountPath: /static/stream
      volumes:
        - name: stream-data
          emptyDir: {}
