apiVersion: v1
kind: Service
metadata:
  name: majesticcoding-service
spec:
  selector:
    app: majesticcoding
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.majesticcoding.port }}
  type: LoadBalancer
