apiVersion: v1
kind: ConfigMap
metadata:
  name: rtmp-nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    rtmp {
        server {
            listen 1935;
            chunk_size 4096;

            application live {
                live on;
                record off;

                hls on;
                hls_path /tmp/hls;
                hls_fragment 3;
                hls_playlist_length 60;
            }
        }
    }

    http {
        include       mime.types;
        default_type  application/octet-stream;

        server {
            listen 8080;

            location / {
                root /tmp/hls;
                add_header Cache-Control no-cache;
                add_header Access-Control-Allow-Origin *;
            }
        }
    }
