replicaCount: 1

image:
  repository: dockerhub.io/mattmajestic/majesticcoding
  tag: "v0.1.0"
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: ""
  hosts:
    - host: app.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}
podAnnotations: {}
