name: Publish Docker Image to Azure Container Registry

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: majesticcoding.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push to Azure Container Registry
        run: |
          docker build -t majesticcoding.azurecr.io/majesticcoding:latest .
          docker push majesticcoding.azurecr.io/majesticcoding:latest
