name: Update @majesticcoding Youtube Channel Metrics

on:
  schedule:
    - cron: '0 0 * * *' # Schedule it to run daily at midnight
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  update_metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2
        with:
          ref: main # Check out the gh-pages branch

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install your notebook dependencies

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --execute --to html majesticcoding-Youtube-Channel.ipynb --output=docs/index.html
        continue-on-error: true

      - name: Configure Git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions"
          git remote set-url origin https://github.com/${{ github.repository }}.git
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Push to Main
        run: |
          git push origin main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
