name: Update @majesticcoding Youtube Channel Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x 

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install your notebook dependencies

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --execute --to html majesticcoding-Youtube-Channel.ipynb --output=docs/index.html
        continue-on-error: true

      - name: Commit and Push HTML Output
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs/index.html
          git commit -m 'Update index.html'
          git push
